export const brandProfiles = [
  { id: "brand-yuantu-auto", name: "远途汽车", englishName: "Yuantu Auto", legalName: "远途汽车科技有限公司", logo: "", description: "专注纯电和增程车型研发、销售与用户服务的新能源汽车品牌。", position: "面向家庭用户的中高端新能源汽车品牌", industry: "新能源汽车", market: "中国大陆", foundedAt: "2018-05-18", headquarters: "上海", slogan: "让每段远途更从容", audience: "一二线城市家庭用户、科技型中产", priceRange: "16-35 万元", site: "yuantu-auto.example.com", aliases: ["远途", "远途 Auto", "Yuantu", "远途新能源"], exclusions: "排除旅游路线、长途出行等非品牌语境中的“远途”普通词。", offerings: 5, competitors: 3, querySets: 4, owner: "李明", status: "正常", updatedAt: "2026-06-18 09:20" },
  { id: "brand-yuantu-commercial", name: "远途商用车", englishName: "Yuantu Commercial", legalName: "远途商用汽车有限公司", logo: "", description: "提供新能源轻型商用车及城市物流解决方案。", position: "覆盖城市配送和中短途物流的新能源商用车品牌", industry: "新能源汽车", market: "中国大陆", foundedAt: "2020-03-12", headquarters: "苏州", slogan: "高效抵达每一程", audience: "城市物流企业、个体运输经营者", priceRange: "12-28 万元", site: "commercial.yuantu.example.com", aliases: ["远途商用", "远途物流车", "Yuantu CV"], exclusions: "“远途汽车”单独出现且没有商用车语境时，不识别为本品牌。", offerings: 3, competitors: 2, querySets: 2, owner: "陈浩", status: "正常", updatedAt: "2026-06-17 16:45" },
  { id: "brand-yuantu-mobility", name: "远途出行", englishName: "Yuantu Mobility", legalName: "远途智慧出行服务有限公司", logo: "", description: "面向企业和个人用户提供租赁、接送及智慧出行服务。", position: "为企业和个人用户提供智能出行服务", industry: "智能出行", market: "中国大陆、东南亚", foundedAt: "2021-08-06", headquarters: "深圳", slogan: "出行，自有远途", audience: "企业客户、商务差旅及品质出行用户", priceRange: "按服务方案计费", site: "mobility.yuantu.example.com", aliases: ["远途出行", "远途租车"], exclusions: "排除泛指远距离出行的普通语义。", offerings: 2, competitors: 4, querySets: 1, owner: "王悦", status: "正常", updatedAt: "2026-06-16 14:10" },
  { id: "brand-yuantu-service", name: "远途服务", englishName: "Yuantu Service", legalName: "远途汽车服务有限公司", logo: "", description: "为远途车主提供售后、补能、救援和会员权益服务。", position: "承接车主服务、补能和售后保障业务", industry: "汽车服务", market: "中国大陆", foundedAt: "2019-11-20", headquarters: "上海", slogan: "服务始终在途", audience: "远途品牌车主及企业车队", priceRange: "按服务项目计费", site: "service.yuantu.example.com", aliases: ["远途售后", "远途车主服务"], exclusions: "没有汽车、车主或售后语境时，不将“远途服务”泛化识别为品牌。", offerings: 2, competitors: 1, querySets: 1, owner: "赵晨", status: "已停用", updatedAt: "2026-06-12 11:30" },
];

export const offeringProfiles = [
  { id: "offering-x7", type: "产品", name: "远途 X7", englishName: "Yuantu X7", brand: "远途汽车", logo: "", category: "中型纯电 SUV", description: "面向家庭用户的中型纯电 SUV。", positioning: "兼顾城市通勤、家庭空间和长途舒适性", aliases: ["X7", "远途纯电 SUV"], exclusions: "单独出现 X7 且没有汽车语境时不识别。", audience: "城市家庭用户", market: "中国大陆", officialPage: "yuantu-auto.example.com/x7", launchedAt: "2025-09-20", status: "在售", owner: "李明", price: "22.8-28.6 万", modelCode: "YT-X7", useCases: "城市通勤、家庭出游", deliveryMode: "", billingMode: "", serviceArea: "", serviceCommitment: "", querySets: 3, knowledgeCount: 12, updatedAt: "2026-06-18 09:20" },
  { id: "offering-m5", type: "产品", name: "远途 M5", englishName: "Yuantu M5", brand: "远途汽车", logo: "", category: "紧凑型纯电 SUV", description: "适合年轻家庭和首次购车用户的纯电 SUV。", positioning: "入门预算下的高效补能和智能座舱", aliases: ["M5", "远途入门 SUV"], exclusions: "排除手机、芯片等其他行业中的 M5 型号。", audience: "年轻家庭、首次购车用户", market: "中国大陆", officialPage: "yuantu-auto.example.com/m5", launchedAt: "2026-03-15", status: "在售", owner: "李明", price: "16.9-21.8 万", modelCode: "YT-M5", useCases: "日常通勤、短途出游", deliveryMode: "", billingMode: "", serviceArea: "", serviceCommitment: "", querySets: 2, knowledgeCount: 8, updatedAt: "2026-06-17 15:30" },
  { id: "offering-shuttle", type: "服务", name: "企业接送服务", englishName: "Corporate Shuttle", brand: "远途出行", logo: "", category: "企业出行服务", description: "为企业提供员工通勤、商务接待和定制线路服务。", positioning: "稳定、可管理的企业用车服务", aliases: ["企业班车", "远途接送", "企业用车"], exclusions: "排除企业自行组织且非远途提供的接送服务。", audience: "中大型企业行政与员工", market: "中国大陆重点城市", officialPage: "mobility.yuantu.example.com/corporate", launchedAt: "2024-06-01", status: "服务中", owner: "王悦", price: "按线路和车辆数报价", modelCode: "", useCases: "", deliveryMode: "线上预约 + 线下交付", billingMode: "项目制 / 月度结算", serviceArea: "上海、深圳、杭州、苏州", serviceCommitment: "核心城市 7×24 小时调度响应", querySets: 2, knowledgeCount: 6, updatedAt: "2026-06-18 08:40" },
  { id: "offering-rescue", type: "服务", name: "道路救援服务", englishName: "Roadside Assistance", brand: "远途服务", logo: "", category: "车主保障服务", description: "为远途车主提供拖车、搭电、换胎和应急补能服务。", positioning: "覆盖核心用车风险的全天候保障服务", aliases: ["远途救援", "24 小时救援", "道路救援"], exclusions: "非远途官方或授权服务商提供的救援不计入。", audience: "远途品牌车主", market: "中国大陆", officialPage: "service.yuantu.example.com/rescue", launchedAt: "2023-01-10", status: "服务中", owner: "赵晨", price: "权益内免费 / 超出范围按次收费", modelCode: "", useCases: "", deliveryMode: "热线、App、上门服务", billingMode: "权益制 / 按次", serviceArea: "全国 300+ 城市", serviceCommitment: "核心城市 30 分钟响应", querySets: 1, knowledgeCount: 9, updatedAt: "2026-06-16 11:20" },
  { id: "offering-fleet", type: "服务", name: "智能车队解决方案", englishName: "Smart Fleet Solution", brand: "远途商用车", logo: "", category: "车队数字化解决方案", description: "面向物流企业提供车辆、调度、能耗和维保一体化管理。", positioning: "降低新能源商用车队全生命周期运营成本", aliases: ["远途车队管理", "智能车队", "Fleet Solution"], exclusions: "单独的车队管理软件且未包含远途服务时不识别。", audience: "物流企业、城市配送车队", market: "中国大陆", officialPage: "commercial.yuantu.example.com/fleet", launchedAt: "2026-04-20", status: "预售", owner: "陈浩", price: "按车队规模报价", modelCode: "", useCases: "", deliveryMode: "SaaS + 项目实施", billingMode: "订阅制 / 项目制", serviceArea: "全国", serviceCommitment: "工作日 2 小时内技术响应", querySets: 1, knowledgeCount: 4, updatedAt: "2026-06-15 17:10" },
];

export const externalCompetitorObjects = [
  { id: "external-zhixing", level: "品牌", name: "智行汽车", brand: "智行汽车", category: "新能源汽车品牌", site: "zhixing.example.com", aliases: ["智行", "Zhixing"], description: "覆盖中高端纯电和增程车型的新能源汽车品牌。" },
  { id: "external-s6", level: "产品", name: "智行 S6", brand: "智行汽车", category: "中型纯电 SUV", site: "zhixing.example.com/s6", aliases: ["S6", "智行纯电 SUV"], description: "面向城市家庭用户的中型纯电 SUV。" },
  { id: "external-yuejie", level: "品牌", name: "跃界汽车", brand: "跃界汽车", category: "新能源汽车品牌", site: "yuejie.example.com", aliases: ["跃界", "Yuejie"], description: "主打年轻家庭和智能化体验的新能源汽车品牌。" },
  { id: "external-business-mobility", level: "服务", name: "智行企业用车", brand: "智行出行", category: "企业出行服务", site: "mobility.zhixing.example.com", aliases: ["智行企业出行", "智行企业接送"], description: "提供企业接送、商务用车和定制线路服务。" },
];

export const competitorRelations = [
  { id: "relation-brand-zhixing", ownBrand: "远途汽车", ownOffering: "", competitorId: "external-zhixing", level: "品牌", relationType: "直接竞品", scenario: "新能源品牌认知", overlap: "中高端新能源家庭市场", audience: "一二线城市家庭用户", priority: "高", owner: "李明", status: "已启用", updatedAt: "2026-06-18 09:30", description: "品牌声量与家庭用户心智高度重叠。" },
  { id: "relation-x7-s6", ownBrand: "远途汽车", ownOffering: "远途 X7", competitorId: "external-s6", level: "产品", relationType: "直接竞品", scenario: "25 万级纯电 SUV 选购", overlap: "价格、尺寸和家庭用车场景", audience: "25 万预算的家庭购车用户", priority: "高", owner: "李明", status: "已启用", updatedAt: "2026-06-17 16:20", description: "核心配置、续航和智能驾驶对比频繁。" },
  { id: "relation-brand-yuejie", ownBrand: "远途汽车", ownOffering: "", competitorId: "external-yuejie", level: "品牌", relationType: "潜在竞品", scenario: "年轻家庭购车", overlap: "年轻家庭和智能化卖点", audience: "年轻家庭用户", priority: "中", owner: "陈浩", status: "已启用", updatedAt: "2026-06-16 11:10", description: "部分 Query 中开始与远途汽车共同出现。" },
  { id: "relation-shuttle", ownBrand: "远途出行", ownOffering: "企业接送服务", competitorId: "external-business-mobility", level: "服务", relationType: "直接竞品", scenario: "企业员工通勤", overlap: "企业班车、商务接待、定制线路", audience: "中大型企业行政部门", priority: "高", owner: "王悦", status: "已停用", updatedAt: "2026-06-12 14:40", description: "服务城市和交付模式高度重叠。" },
];

export const knowledgeMaterials = [
  { id: "material-text-range", mediaType: "文本", businessType: "产品 / 服务事实", title: "远途 X7 城市通勤续航", brand: "远途汽车", offering: "远途 X7", sourceType: "链接导入", sourceUrl: "https://yuantu-auto.example.com/x7/range", sourceName: "远途 X7 官方技术白皮书", status: "已生效", updatedAt: "2026-06-18 09:20", owner: "李明", summary: "CLTC 续航 650km，城区通勤实测平均能耗 13.8kWh/100km。", markdown: "# 远途 X7 城市通勤续航\n\n远途 X7 CLTC 续航为 **650km**。\n\n## 城区实测\n\n城区通勤实测平均能耗为 13.8kWh/100km。", imageItems: [] },
  { id: "material-image-space", mediaType: "图片集", businessType: "产品 / 服务事实", title: "远途 X7 空间官方图片", brand: "远途汽车", offering: "远途 X7", sourceType: "链接导入", sourceUrl: "https://yuantu-auto.example.com/x7/space", sourceName: "远途 X7 官方产品页", status: "已生效", updatedAt: "2026-06-17 15:40", owner: "李明", summary: "包含二排空间、后备箱和儿童座椅安装区域图片。", markdown: "", imageItems: [{ id: "image-space-row2", url: "", title: "二排空间实拍", description: "远途 X7 二排座椅及腿部空间官方实拍。", altText: "远途 X7 浅色内饰二排空间", ocrText: "二排腿部空间 980mm", fileMeta: "JPG · 2400×1600 · 1.8MB" }, { id: "image-space-trunk", url: "", title: "后备箱空间", description: "远途 X7 后备箱装载空间展示。", altText: "远途 X7 后备箱空间", ocrText: "后备箱容积 620L", fileMeta: "JPG · 2400×1600 · 1.6MB" }] },
  { id: "material-text-service", mediaType: "文本", businessType: "政策与权益", title: "远途汽车售后政策", brand: "远途汽车", offering: "道路救援服务", sourceType: "手动创建", sourceUrl: "", sourceName: "远途汽车服务权益页", status: "已生效", updatedAt: "2026-06-16 11:20", owner: "赵晨", summary: "核心城市提供 24 小时道路救援，三电系统质保 8 年或 16 万公里。", markdown: "# 远途汽车售后政策\n\n- 核心城市提供 24 小时道路救援\n- 三电系统质保 8 年或 16 万公里", imageItems: [] },
  { id: "material-image-rescue", mediaType: "图片集", businessType: "媒体素材", title: "道路救援服务素材", brand: "远途服务", offering: "道路救援服务", sourceType: "手动创建", sourceUrl: "", sourceName: "品牌服务资料", status: "草稿", updatedAt: "2026-06-15 17:10", owner: "赵晨", summary: "道路救援服务流程和现场服务图片。", markdown: "", imageItems: [{ id: "image-rescue-flow", url: "", title: "道路救援服务流程图", description: "从提交救援申请到服务完成的四步流程。", altText: "远途道路救援服务流程图", ocrText: "提交申请、确认位置、服务响应、完成救援", fileMeta: "PNG · 1600×900 · 820KB" }, { id: "image-rescue-scene", url: "", title: "道路救援现场", description: "服务人员进行应急搭电。", altText: "远途道路救援服务人员现场搭电", ocrText: "24 小时道路救援", fileMeta: "JPG · 2000×1333 · 1.2MB" }] },
  { id: "material-text-expired", mediaType: "文本", businessType: "过期说法", title: "2024 款旧补能政策", brand: "远途汽车", offering: "远途 X7", sourceType: "链接导入", sourceUrl: "https://yuantu-auto.example.com/archive/charging-2024", sourceName: "历史官网活动页", status: "已过期", updatedAt: "2025-12-31 18:00", owner: "李明", summary: "该权益已在 2026 年 1 月更新，引用时需要标记为过期。", markdown: "# 2024 款旧补能政策\n\n该政策已经失效，仅供历史事实核对。", imageItems: [] },
];
