// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/content/accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/content/accounts">> = Specific
  const handler = {} as typeof import("../../src/app/content/accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/content/library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/content/library">> = Specific
  const handler = {} as typeof import("../../src/app/content/library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/content/publish/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/content/publish/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/content/publish/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/content/publish/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/content/publish/new">> = Specific
  const handler = {} as typeof import("../../src/app/content/publish/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/content/publish/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/content/publish">> = Specific
  const handler = {} as typeof import("../../src/app/content/publish/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/monitor/brands/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitor/brands">> = Specific
  const handler = {} as typeof import("../../src/app/monitor/brands/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/monitor/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitor/compare">> = Specific
  const handler = {} as typeof import("../../src/app/monitor/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/monitor/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitor/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/monitor/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/monitor/queries/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitor/queries/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/monitor/queries/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/monitor/queries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitor/queries">> = Specific
  const handler = {} as typeof import("../../src/app/monitor/queries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/monitor/tasks/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitor/tasks/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/monitor/tasks/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/monitor/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitor/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/monitor/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
